//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPG_Distribution_System.CustomerMgntRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AadharNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIFSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistributorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PinNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RashanCardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TalukaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AadharNo {
            get {
                return this.AadharNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AadharNoField, value) != true)) {
                    this.AadharNoField = value;
                    this.RaisePropertyChanged("AadharNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNo {
            get {
                return this.BankAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNoField, value) != true)) {
                    this.BankAccountNoField = value;
                    this.RaisePropertyChanged("BankAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankIFSC {
            get {
                return this.BankIFSCField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIFSCField, value) != true)) {
                    this.BankIFSCField = value;
                    this.RaisePropertyChanged("BankIFSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTypeField, value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistributorCode {
            get {
                return this.DistributorCodeField;
            }
            set {
                if ((this.DistributorCodeField.Equals(value) != true)) {
                    this.DistributorCodeField = value;
                    this.RaisePropertyChanged("DistributorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PinNo {
            get {
                return this.PinNoField;
            }
            set {
                if ((this.PinNoField.Equals(value) != true)) {
                    this.PinNoField = value;
                    this.RaisePropertyChanged("PinNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RashanCardNo {
            get {
                return this.RashanCardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RashanCardNoField, value) != true)) {
                    this.RashanCardNoField = value;
                    this.RaisePropertyChanged("RashanCardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Taluka {
            get {
                return this.TalukaField;
            }
            set {
                if ((object.ReferenceEquals(this.TalukaField, value) != true)) {
                    this.TalukaField = value;
                    this.RaisePropertyChanged("Taluka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerMgntRef.ICustomerMgnt")]
    public interface ICustomerMgnt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/AddCustomer", ReplyAction="http://tempuri.org/ICustomerMgnt/AddCustomerResponse")]
        LPG_Distribution_System.CustomerMgntRef.Customer AddCustomer(LPG_Distribution_System.CustomerMgntRef.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/AddCustomer", ReplyAction="http://tempuri.org/ICustomerMgnt/AddCustomerResponse")]
        System.Threading.Tasks.Task<LPG_Distribution_System.CustomerMgntRef.Customer> AddCustomerAsync(LPG_Distribution_System.CustomerMgntRef.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomer", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomerResponse")]
        LPG_Distribution_System.CustomerMgntRef.Customer GetCustomer(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomer", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomerResponse")]
        System.Threading.Tasks.Task<LPG_Distribution_System.CustomerMgntRef.Customer> GetCustomerAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomersName", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomersNameResponse")]
        string[] GetCustomersName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomersName", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomersNameResponse")]
        System.Threading.Tasks.Task<string[]> GetCustomersNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomersTypes", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomersTypesResponse")]
        string[] GetCustomersTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerMgnt/GetCustomersTypes", ReplyAction="http://tempuri.org/ICustomerMgnt/GetCustomersTypesResponse")]
        System.Threading.Tasks.Task<string[]> GetCustomersTypesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerMgntChannel : LPG_Distribution_System.CustomerMgntRef.ICustomerMgnt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerMgntClient : System.ServiceModel.ClientBase<LPG_Distribution_System.CustomerMgntRef.ICustomerMgnt>, LPG_Distribution_System.CustomerMgntRef.ICustomerMgnt {
        
        public CustomerMgntClient() {
        }
        
        public CustomerMgntClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerMgntClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerMgntClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerMgntClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LPG_Distribution_System.CustomerMgntRef.Customer AddCustomer(LPG_Distribution_System.CustomerMgntRef.Customer customer) {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<LPG_Distribution_System.CustomerMgntRef.Customer> AddCustomerAsync(LPG_Distribution_System.CustomerMgntRef.Customer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public LPG_Distribution_System.CustomerMgntRef.Customer GetCustomer(string name) {
            return base.Channel.GetCustomer(name);
        }
        
        public System.Threading.Tasks.Task<LPG_Distribution_System.CustomerMgntRef.Customer> GetCustomerAsync(string name) {
            return base.Channel.GetCustomerAsync(name);
        }
        
        public string[] GetCustomersName() {
            return base.Channel.GetCustomersName();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCustomersNameAsync() {
            return base.Channel.GetCustomersNameAsync();
        }
        
        public string[] GetCustomersTypes() {
            return base.Channel.GetCustomersTypes();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCustomersTypesAsync() {
            return base.Channel.GetCustomersTypesAsync();
        }
    }
}
