//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.AzureModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public int DistributorCode { get; set; }
        public string CustomerName { get; set; }
        public string Gender { get; set; }
        public string CustomerType { get; set; }
        public string AadharNo { get; set; }
        public string RashanCardNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int PinNo { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string BankIFSC { get; set; }
        public string BankAccountNo { get; set; }
        public int Id { get; set; }
    }
}
