//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.AzureModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public int DistributorCode { get; set; }
        public int C14_2_KG_With_Subsidy__E_ { get; set; }
        public int C14_2_KG_With_Subsidy__F_ { get; set; }
        public int C14_2_KG_Without_Subsidy__E_ { get; set; }
        public int C14_2_KG_Without_Subsidy__F_ { get; set; }
        public int C19_KG_Industrial__E_ { get; set; }
        public int C19_KG_Industrial__F_ { get; set; }
        public int C5_KG__E_ { get; set; }
        public int C5_KG__F_ { get; set; }
    }
}
