//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService2.AzureModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxCylinder
    {
        public int TxId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime TxDate { get; set; }
        public string CylinderDetails { get; set; }
        public int Quentity { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public double CGST { get; set; }
        public double SGST { get; set; }
        public double Total { get; set; }
        public int CashMemoNo { get; set; }
        public int Id { get; set; }
        public Nullable<int> DistributorCode { get; set; }
    }
}
