//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPG_Distribution_System.AccountingRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TxCylinder", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class TxCylinder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CashMemoNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CylinderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TxDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TxIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CGST {
            get {
                return this.CGSTField;
            }
            set {
                if ((this.CGSTField.Equals(value) != true)) {
                    this.CGSTField = value;
                    this.RaisePropertyChanged("CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CashMemoNo {
            get {
                return this.CashMemoNoField;
            }
            set {
                if ((this.CashMemoNoField.Equals(value) != true)) {
                    this.CashMemoNoField = value;
                    this.RaisePropertyChanged("CashMemoNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CylinderDetails {
            get {
                return this.CylinderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.CylinderDetailsField, value) != true)) {
                    this.CylinderDetailsField = value;
                    this.RaisePropertyChanged("CylinderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quentity {
            get {
                return this.QuentityField;
            }
            set {
                if ((this.QuentityField.Equals(value) != true)) {
                    this.QuentityField = value;
                    this.RaisePropertyChanged("Quentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SGST {
            get {
                return this.SGSTField;
            }
            set {
                if ((this.SGSTField.Equals(value) != true)) {
                    this.SGSTField = value;
                    this.RaisePropertyChanged("SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TxDate {
            get {
                return this.TxDateField;
            }
            set {
                if ((this.TxDateField.Equals(value) != true)) {
                    this.TxDateField = value;
                    this.RaisePropertyChanged("TxDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TxId {
            get {
                return this.TxIdField;
            }
            set {
                if ((this.TxIdField.Equals(value) != true)) {
                    this.TxIdField = value;
                    this.RaisePropertyChanged("TxId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TxStoveRegulator", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class TxStoveRegulator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CashMemoNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SGSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TxDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TxIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CGST {
            get {
                return this.CGSTField;
            }
            set {
                if ((this.CGSTField.Equals(value) != true)) {
                    this.CGSTField = value;
                    this.RaisePropertyChanged("CGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CashMemoNo {
            get {
                return this.CashMemoNoField;
            }
            set {
                if ((this.CashMemoNoField.Equals(value) != true)) {
                    this.CashMemoNoField = value;
                    this.RaisePropertyChanged("CashMemoNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quentity {
            get {
                return this.QuentityField;
            }
            set {
                if ((this.QuentityField.Equals(value) != true)) {
                    this.QuentityField = value;
                    this.RaisePropertyChanged("Quentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SGST {
            get {
                return this.SGSTField;
            }
            set {
                if ((this.SGSTField.Equals(value) != true)) {
                    this.SGSTField = value;
                    this.RaisePropertyChanged("SGST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TxDate {
            get {
                return this.TxDateField;
            }
            set {
                if ((this.TxDateField.Equals(value) != true)) {
                    this.TxDateField = value;
                    this.RaisePropertyChanged("TxDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TxId {
            get {
                return this.TxIdField;
            }
            set {
                if ((this.TxIdField.Equals(value) != true)) {
                    this.TxIdField = value;
                    this.RaisePropertyChanged("TxId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountingRef.IAccounting")]
    public interface IAccounting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccounting/GetTxCylinders", ReplyAction="http://tempuri.org/IAccounting/GetTxCylindersResponse")]
        LPG_Distribution_System.AccountingRef.TxCylinder[] GetTxCylinders(System.DateTime from, System.DateTime to, string cyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccounting/GetTxCylinders", ReplyAction="http://tempuri.org/IAccounting/GetTxCylindersResponse")]
        System.Threading.Tasks.Task<LPG_Distribution_System.AccountingRef.TxCylinder[]> GetTxCylindersAsync(System.DateTime from, System.DateTime to, string cyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccounting/GetTxStoveRegulators", ReplyAction="http://tempuri.org/IAccounting/GetTxStoveRegulatorsResponse")]
        LPG_Distribution_System.AccountingRef.TxStoveRegulator[] GetTxStoveRegulators(System.DateTime from, System.DateTime to, string cyType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccounting/GetTxStoveRegulators", ReplyAction="http://tempuri.org/IAccounting/GetTxStoveRegulatorsResponse")]
        System.Threading.Tasks.Task<LPG_Distribution_System.AccountingRef.TxStoveRegulator[]> GetTxStoveRegulatorsAsync(System.DateTime from, System.DateTime to, string cyType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountingChannel : LPG_Distribution_System.AccountingRef.IAccounting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingClient : System.ServiceModel.ClientBase<LPG_Distribution_System.AccountingRef.IAccounting>, LPG_Distribution_System.AccountingRef.IAccounting {
        
        public AccountingClient() {
        }
        
        public AccountingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LPG_Distribution_System.AccountingRef.TxCylinder[] GetTxCylinders(System.DateTime from, System.DateTime to, string cyType) {
            return base.Channel.GetTxCylinders(from, to, cyType);
        }
        
        public System.Threading.Tasks.Task<LPG_Distribution_System.AccountingRef.TxCylinder[]> GetTxCylindersAsync(System.DateTime from, System.DateTime to, string cyType) {
            return base.Channel.GetTxCylindersAsync(from, to, cyType);
        }
        
        public LPG_Distribution_System.AccountingRef.TxStoveRegulator[] GetTxStoveRegulators(System.DateTime from, System.DateTime to, string cyType) {
            return base.Channel.GetTxStoveRegulators(from, to, cyType);
        }
        
        public System.Threading.Tasks.Task<LPG_Distribution_System.AccountingRef.TxStoveRegulator[]> GetTxStoveRegulatorsAsync(System.DateTime from, System.DateTime to, string cyType) {
            return base.Channel.GetTxStoveRegulatorsAsync(from, to, cyType);
        }
    }
}
