//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPG_Distribution_System.SynchroRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Synchro", Namespace="http://schemas.datacontract.org/2004/07/WcfService2.Synchronization")]
    [System.SerializableAttribute()]
    public partial class Synchro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((this.RecordIdField.Equals(value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchroRef.ISynchronization")]
    public interface ISynchronization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/AddRecord", ReplyAction="http://tempuri.org/ISynchronization/AddRecordResponse")]
        void AddRecord(string tnm, string op, int rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/AddRecord", ReplyAction="http://tempuri.org/ISynchronization/AddRecordResponse")]
        System.Threading.Tasks.Task AddRecordAsync(string tnm, string op, int rid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/GetRecords", ReplyAction="http://tempuri.org/ISynchronization/GetRecordsResponse")]
        LPG_Distribution_System.SynchroRef.Synchro[] GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/GetRecords", ReplyAction="http://tempuri.org/ISynchronization/GetRecordsResponse")]
        System.Threading.Tasks.Task<LPG_Distribution_System.SynchroRef.Synchro[]> GetRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/SynchroToCentralDB", ReplyAction="http://tempuri.org/ISynchronization/SynchroToCentralDBResponse")]
        string SynchroToCentralDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronization/SynchroToCentralDB", ReplyAction="http://tempuri.org/ISynchronization/SynchroToCentralDBResponse")]
        System.Threading.Tasks.Task<string> SynchroToCentralDBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISynchronizationChannel : LPG_Distribution_System.SynchroRef.ISynchronization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronizationClient : System.ServiceModel.ClientBase<LPG_Distribution_System.SynchroRef.ISynchronization>, LPG_Distribution_System.SynchroRef.ISynchronization {
        
        public SynchronizationClient() {
        }
        
        public SynchronizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddRecord(string tnm, string op, int rid) {
            base.Channel.AddRecord(tnm, op, rid);
        }
        
        public System.Threading.Tasks.Task AddRecordAsync(string tnm, string op, int rid) {
            return base.Channel.AddRecordAsync(tnm, op, rid);
        }
        
        public LPG_Distribution_System.SynchroRef.Synchro[] GetRecords() {
            return base.Channel.GetRecords();
        }
        
        public System.Threading.Tasks.Task<LPG_Distribution_System.SynchroRef.Synchro[]> GetRecordsAsync() {
            return base.Channel.GetRecordsAsync();
        }
        
        public string SynchroToCentralDB() {
            return base.Channel.SynchroToCentralDB();
        }
        
        public System.Threading.Tasks.Task<string> SynchroToCentralDBAsync() {
            return base.Channel.SynchroToCentralDBAsync();
        }
    }
}
